# <span style="color: gold"> Pytorch Tutorial

## <span style="color: orange">Importing Torch

In [4]:
import torch

## <span style="color: lightgreen">The Basics of Tensors

###  <span style="color:cyan">Create a tensor with specified item `torch.tensor(array/list)` 

In [5]:
tensor = torch.tensor([1, 2, 3])

### <span style="color: cyan"> Create a random tensor </span> `torch.rand(dim1, dim2, dim...)` 

In [6]:
tensor_r = torch.rand(1, 9)
tensor_r, tensor_r.shape

(tensor([[0.0551, 0.2932, 0.5755, 0.4841, 0.7625, 0.9607, 0.7396, 0.1297, 0.4664]]),
 torch.Size([1, 9]))

### <span style="color: cyan"> Remove all single dimension of a tensor  </span>`tensor.squeeze()` 

In [7]:
tensor_s = tensor_r.squeeze()
tensor_s, tensor_s.shape

(tensor([0.0551, 0.2932, 0.5755, 0.4841, 0.7625, 0.9607, 0.7396, 0.1297, 0.4664]),
 torch.Size([9]))

### <span style="color:cyan"> Add a single dimension to a target tensor at a specific dimension </span>`tensor.unsqueeze(dim)` 

In [8]:
tensor_r_un = tensor_r.unsqueeze(0)
tensor_r_un, tensor_r_un.shape

(tensor([[[0.0551, 0.2932, 0.5755, 0.4841, 0.7625, 0.9607, 0.7396, 0.1297,
           0.4664]]]),
 torch.Size([1, 1, 9]))

### <span style="color:cyan" >Rearrange dimensions of a tensor </span>`torch.permute()` -> arrange the first parameter to the first dim

In [9]:
tensor = torch.randn(3, 4)
torch.permute(tensor, (1, 0)).shape

torch.Size([4, 3])

#### <span style="color: lime"> Both tensors (before and after permuting) shares the same memory location

In [10]:
# Example
image_tensor = torch.randn(224, 244, 3)  # Height, Width, Channels
# Permute to Channels, Height, Width
permuted_tensor = torch.permute(image_tensor, (2, 0, 1))
permuted_tensor.shape 

torch.Size([3, 224, 244])

### <span style="color:lightgreen"> Indexing (selecting data from tensor)

In [11]:
import torch
x = torch.arange(1, 10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x = x.reshape(1, 3, 3)

In [13]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
x[0, 0] # = x[0][0]

tensor([1, 2, 3])

In [15]:
x[0][0][0], x[0, 2, 2]

(tensor(1), tensor(9))

In [16]:
x[0, :, 1] # : -> all elements in that dimension

tensor([2, 5, 8])

In [17]:
x[0, 0, :]

tensor([1, 2, 3])

### <span style="color:lightgreen"> PyTorch tensors & NumPy 

#### Numpy to pytorch `torch.from_numpy(nd_array)`
#### Pytorch to numpy `torch.tensor.numpy()`

In [18]:
import torch
import numpy as np

array = np.arange(1.0, 8.0) # default dtype = float64
tensor = torch.from_numpy(array) # pytorch default dtype = float32 
# pytorch inherits dtype from numpy
# tensor = torch.from_numpy(array).type(torch.float32) to convert to float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [19]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # reflected float32 from pytorch
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### <span style="color:lightgreen"> Reproducibility (trying to take random out of random)

In [20]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(3, 4)
tensor_A, tensor_B

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

### <span style="color:lightgreen"> Using GPU to operate (faster)

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

# Count number of devices
torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU"

'NVIDIA GeForce RTX 4050 Laptop GPU'

In [ ]:
# Create a tensor (default on CPU)
tensor = torch.rand(3, 4)
tensor = tensor.to(device) # Moving tensor to device (in this case GPU)
print(tensor, tensor.device)

tensor([[0.3543, 0.2011, 0.5396, 0.3984],
        [0.5185, 0.7611, 0.0943, 0.8666],
        [0.4837, 0.0613, 0.0564, 0.3538]], device='cuda:0') cuda:0


### <span style="color: lightgreen"> Putting tensor back to cpu `tensor.cpu()`

In [6]:
# If tensor.device is GPU, you can't convert it to numpy directly
tensor = tensor.cpu() # So you can convert it to NumPy
numpy_tensor = tensor.numpy()
numpy_tensor

array([[0.35433   , 0.20106643, 0.5395918 , 0.39841598],
       [0.5184914 , 0.76112026, 0.09426308, 0.86663646],
       [0.48371702, 0.06130838, 0.05644178, 0.35380912]], dtype=float32)

## <span style="color:lightgreen"> Pytorch Workflow